Repository d-edge/Cardizer, pull requests merged in 2021-10, with the labels that each got.

#56 Feature/add laser card
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement, hacktoberfest

#58 Add support for card InstaPayment
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 feat(card): add 2221-2720 to MasterCard
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 Add support for card Diners
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement

#34 Add support for card RuPay
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement

#60 feat(card): improve Discover support
  src/Dedge.Cardizer/Dedge.Cardizer.fs
  src/Tests/Tests.fs
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
